#!/bin/sh


delim='|'


main()
{
	while true; do
		power
		datetime
		xsetroot -name "$delim $battery $delim $date $delim $time $delim"
		sleep 5
		done
}

# Date & Time
datetime()
{
	time=$(date +"%H:%M")
	date=$(date +"%a, %b %d")
}
# Volume


# Power
power()
{
	battery="$(cat /sys/class/power_supply/BAT0/capacity) %"
	timer=""
}

main; exit
