#!/bin/sh


delim='|'


main()
{
	while true; do
		power
		xsetroot -name "$delim $battery $delim"
		sleep 5
		done
}

# Volume


# Power
power() {
	battery="$(cat /sys/class/power_supply/BAT0/capacity) %"
	timer=""
}

main; exit
